### ISSUE TITLE
BaeFell's to-do list

### ISSUE THREAD

**Issue by nfell2009** [skUnity/issues#5]
I always forget what I'm doing...

- [ ] finish admin resources thing
- [ ] support links in element descriptions
- [ ] add element reporting
- [ ] show reported example in activity queue
- [ ] change author of example
- [ ] add reset/delete buttons to addons

**Comment by Nicofisi** [comment]
How is it fixed and won't fix and question and good first issue and fixed and duplicate and bug and can't replicate & confirmed

**Comment by JRoy** [comment]
@Nicofisi it's the best issue so it deserves all tags

**Comment by JRoy** [comment]
bbfell look how cool this is

**Comment by xXAndrew28Xx** [comment]
> Github has "Projects" thing which can make to-do lists in which can even have multiple sections and refer to issues.
> BaeFell proceeds to make an issue 👀
